name: "Build"

on:
  push:
    tags:
      - "*"
permissions:
  contents: write

env:
  PROJECT_NAME: oh-my-git
  GODOT_VERSION: 3.6.2

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: barichello/godot-ci:3.6.2
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: apt-get update && apt-get install -y rsync p7zip make
      - name: Setup
        run: |
          mkdir -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/$GODOT_VERSION.stable ~/.local/share/godot/templates/$GODOT_VERSION.stable
      - name: Build Linux
        run: make linux
      - name: Build macOS
        run: make macos
      - name: Build Windows
        run: make windows
      - name: Clean up
        run: make clean-unzipped
      - name: Publish to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/${{ env.PROJECT_NAME }}-linux.zip
            build/${{ env.PROJECT_NAME }}-macos.zip
            build/${{ env.PROJECT_NAME }}-windows.zip
